---
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          scope: GLOBAL
          id: github-ssh-private-key
          description: GitHub SSH Private Key
          username: jenkins
          passphrase: ""
          privateKeySource:
            directEntry:
              privateKey: ${file:${JENKINS_REF}/id_rsa}
      - usernamePassword:
          scope: GLOBAL
          id: github-oauth-credentials
          description: GitHub Organization OAuth Credentials
          username: ${JCASC_GITHUB_OAUTH_KEY}
          password: ${JCASC_GITHUB_OAUTH_SECRET}