---
unclassified:
  location:
    adminAddress: "jenkins@slashdevops.com"
    url: "${JCASC_CONTROLLER_URL_PROTOCOL}://${JCASC_CONTROLLER_NAME}"
  themeManager:
    disableUserThemes: false
    theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'yyyy-MM-dd'T'HH:mm:ss.SSSXXX'</b> '"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: true
    createAccountBasedOnEmail: true
    disableGitToolChooser: false
    globalConfigEmail: "jenkins@slashdevops.com"
    globalConfigName: "jenkins"
    hideCredentials: true
    showEntireCommitSummaryInChanges: true
    useExistingAccountWithSameEmail: true